---
title: "Clustering : Classif non supervisée"
author: "Groupe 5 (Maeva, Matéo, Mélina, Marine, Anna)"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float: true
    self_contained: true
    df_print: paged
    highlight: tango
    theme:
      version: 4
      bootswatch: flatly
      bg: aliceblue
      fg: '#000000'
      primary: '#6FA8DC'
      base_font: Lato
      heading_font: Playfair Display
      code_font: Fira Code
    tabset: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, fig.height=3, fig.width=4)
```

```{r, include = FALSE}
setwd("E:/IMPORTANT/ECOLE/INH/M2/COURS/Sébastien Lé/Classification non supervisée/Clustering")

sections.path <- file.path(rprojroot::find_root("Clustering.Rproj"),
                           "bilan",
                           "seances")
r.files.vec <- list.files(sections.path)
r.files.vec <- r.files.vec[grepl(".Rmd", r.files.vec)]
```

# Introduction et overview

```{r child = 'seances/intro.Rmd'}

```

# Seance 1

```{r child = 'seances/cours1.Rmd'}

```

# Seance 2

```{r child = 'seances/cours2.Rmd'}

```

# Seance 3

```{r child = 'seances/cours3.Rmd'}

```

# Seance 4

```{r child = 'seances/cours4.Rmd'}

```

# Seance 5

```{r child = 'seances/cours5.Rmd'}

```

# Seance 6

```{r child = 'seances/cours6.Rmd'}

```
